### ISSUE TITLE
microUPDI Firmware Uploader does not compile in IDE 2.3.6

### ISSUE THREAD

**Issue by ahahn61** [MCUdude/microUPDI#24]
I tried latest Arduino IDE 2.3.6 and failed to compile "microUPDI Firmware Uploader".

```
FQBN: microUPDIcore:avr:microupdi
Using board 'microupdi' from platform in folder: D:\ahahn\AppData\Local\Arduino15\packages\microUPDIcore\hardware\avr\1.0.3
Using core 'arduino' from platform in folder: D:\ahahn\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.8.6

Detecting libraries used...
D:\ahahn\AppData\Local\Arduino15\packages\microUPDIcore\hardware\avr\1.0.3/scripts/dummy-preproc-macros-command.bat C:\Users\ahahn\AppData\Local\arduino\sketches\BEA572CD21859ADFED402CDF7313A721/preproc ctags_target_for_gcc_minus_e.cpp
Error while detecting libraries included by C:\Users\ahahn\AppData\Local\arduino\sketches\BEA572CD21859ADFED402CDF7313A721\sketch\ProMicro.ino.cpp
Generating function prototypes...
Das System kann den angegebenen Pfad nicht finden.
D:\ahahn\AppData\Local\Arduino15\packages\microUPDIcore\hardware\avr\1.0.3/scripts/dummy-preproc-macros-command.bat C:\Users\ahahn\AppData\Local\arduino\sketches\BEA572CD21859ADFED402CDF7313A721/preproc ctags_target_for_gcc_minus_e.cpp
exit status 1

Compilation error: exit status 1
```

As a workaround I downgraded to Arduino 1.8.19 with microIPDIcore 1.0.2, which worked as expected.
regards
Alois

**Comment by JanVelas** [comment]
I confirm this to be happening on Arduino IDE 2.3.7 as well.
I tried manually creating the folder "preproc" under the sketch folder, which got me past the first error, but I wasn't able solve the error that comes after that:
> open C:\Users\<insert your username>\AppData\Local\Temp\529982088\sketch_merged.cpp: The system cannot find the file specified.

**Comment by felias-fogg** [comment]
Similar error messages for Arduino IDE 2.3.8 here:

```
FQBN: microUPDIcore:avr:microupdi
Using board 'microupdi' from platform in folder: /Users/nebel/Library/Arduino15/packages/microUPDIcore/hardware/avr/1.0.3
Using core 'arduino' from platform in folder: /Users/nebel/Library/Arduino15/packages/arduino/hardware/avr/1.8.7

mkdir: /Users/nebel/Library/Caches/arduino/sketches/4758DE70E8CEB46A193CE632EC9A4046/preproc: File exists
Detecting libraries used...
/Users/nebel/Library/Arduino15/packages/microUPDIcore/hardware/avr/1.0.3/scripts/dummy-preproc-macros-command.sh /Users/nebel/Library/Caches/arduino/sketches/4758DE70E8CEB46A193CE632EC9A4046/preproc ctags_target_for_gcc_minus_e.cpp
Generating function prototypes...
/Users/nebel/Library/Arduino15/packages/microUPDIcore/hardware/avr/1.0.3/scripts/dummy-preproc-macros-command.sh /Users/nebel/Library/Caches/arduino/sketches/4758DE70E8CEB46A193CE632EC9A4046/preproc ctags_target_for_gcc_minus_e.cpp
open /private/var/folders/qh/ydvbb4kd62bczfh7twhr5rhw0000gn/T/1756735288/sketch_merged.cpp: no such file or directory

Compilation error: open /private/var/folders/qh/ydvbb4kd62bczfh7twhr5rhw0000gn/T/1756735288/sketch_merged.cpp: no such file or directory
```

**Comment by felias-fogg** [comment]
I had a look into it, and the reason is that `ctags`  is called on the mentioned file. I tried to generate the needed file in the dummy script, but failed somehow.  

The easy thing would be to say that it only works with IDE 1. Apart from that, the simplest solution would be to revert to a normal compilation and disregard the results. Another option may be to use a self-sufficient uploader (as I did for dw-link). Or, my preferred solution, to tell people to use avrdude to upload the firmware. If you are building your own programmer/debugger, you probably know your way around.
